# -*- coding: utf-8 -*-
"""Data_Fundamental_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VFdhVycbPzD7InqNVDRfjynlCF7le8WL
"""

import pandas as pd

# Load dataset
df = pd.read_csv("/content/customer.csv")

# Create total_purchase column
df["total_purchase"] = df["quantity"] * df["price"]

# Show data
print(df)

# Top customers (highest spending)
top_customers = df.groupby("customer_name")["total_purchase"].sum().sort_values(ascending=False)
print("\nTop Customers:\n", top_customers)

# Product popularity (by quantity)
product_popularity = df.groupby("product")["quantity"].sum().sort_values(ascending=False)
print("\nProduct Popularity:\n", product_popularity)